<?php

namespace Database\Seeders;

use App\Models\PuppyPattern;
use Illuminate\Database\Seeder;

class PatternSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patterns = [
            'Brindle',
            'Merle',
            'Solid Black',
            'Solid White',
            'Solid Brown',
            'Solid Blue',
            'Solid Red',
            'Solid Cream',
            'Black and Tan',
            'Black and White',
            'Brown and White',
            'Blue and White',
            'Red and White',
            'Cream and White',
            'Sable',
            'Fawn',
            'Piebald',
            'Harlequin',
            'Ticked',
            'Roan',
            'Spotted',
            'Parti',
            'Phantom',
            'Blue Merle',
            'Red Merle',
            'Chocolate Merle',
            'Lilac Merle',
            'Tricolor',
            'Bicolor',
            'Agouti',
            'Tan Points',
            'White Markings',
            'Mask',
            'Saddle',
            'Plush',
            'Tiger Striped',
            'Marbled',
            'Feathered',
            'Silver',
            'Golden',
            'Chocolate',
            'Champagne',
            'Isabella',
            'Seal',
            'Mosaic',
            'Frosted',
            'Grizzle',
            'Brindled Blue',
            'Brindled Red',
            'Wolf Sable',
            'Black Sable',
            'Red Sable',
            'Cream Sable',
            'Blue Sable',
            'Chocolate Sable',
            'Domino',
            'Irish Marked',
            'Split Face',
            'Maskless',
            'Full Mask',
            'Blenheim',
            'Tri Split',
            'Hound Marked',
            'Dilute',
            'Reverse Brindle',
            'Shadow Brindle',
            'Silver Brindle',
            'Tan Brindle',
            'Chocolate Brindle',
            'Red Brindle',
            'Lilac Brindle',
            'Merle Brindle',
            'Fawn Brindle',
            'Blue Brindle',
            'Blue Fawn',
            'Blue and Tan',
            'Blue and Gold',
            'Lilac',
            'Liver',
            'Smoky',
            'White and Liver',
            'White and Lilac',
            'White and Chocolate',
            'White and Seal',
            'Platinum',
            'Bronze',
            'Coffee',
            'Cinnamon',
            'Honey',
            'Caramel',
            'Mocha',
            'Almond',
            'Latte',
            'Sandy',
            'Pearl',
            'Ivory',
            'Slate',
            'Ash',
            'Graphite',
            'Charcoal',
            'Ebony',
            'Onyx',
            'Obsidian',
            'Cinder',
            'Storm',
            'Hickory',
            'Pine',
            'Chestnut',
            'Maple',
            'Hazel',
            'Walnut',
            'Mahogany',
            'Cherry',
            'Ginger',
            'Amber',
            'Copper',
            'Rust',
            'Clay',
            'Brick',
            'Crimson',
            'Scarlet',
            'Berry',
            'Wine',
            'Grape',
            'Lavender',
            'Orchid',
            'Lilac Frost',
            'Amethyst',
            'Rose Gold',
            'Goldenrod',
            'Marigold',
            'Dandelion',
            'Buttercream',
            'Alabaster',
            'Bone',
            'Driftwood',
            'Sand Dune',
            'Desert',
            'Oatmeal',
            'Sunset',
            'Harvest',
            'Autumn',
            'Smoke',
            'Fog',
            'Misty',
            'Aurora',
            'Twilight',
            'Evening',
            'Dusk',
            'Midnight',
            'Eclipse',
            'Galaxy',
            'Stardust',
            'Comet',
            'Meteor',
            'Nebula',
            'Cosmos',
            'Celestial',
            'Lunar',
            'Solar',
            'Sunbeam',
            'Daylight',
            'Moonlight',
            'Shadow',
            'Ghost',
            'Specter',
            'Phantom Frost',
            'Ethereal',
            'Mystic',
            'Enigma',
            'Secret',
            'Magic',
            'Dream',
            'Fantasy',
            'Mirage',
            'Illusion',
            'Vision',
            'Echo',
            'Whisper',
            'Breeze',
            'Zephyr',
            'Flame',
            'Inferno',
            'Ember',
            'Blaze',
            'Ashes',
            'Flicker',
            'Spark',
            'Firefly',
            'Glow',
            'Radiance',
            'Halo',
            'Aura',
            'Nimbus',
            'Cloud',
            'Rain',
            'Stormy',
            'Thunder',
            'Lightning',
            'Flash',
            'Bolt',
            'Pulse',
            'Current',
            'Ripple',
            'Tide',
            'Wave',
            'Ocean',
            'Seafoam',
            'Coral',
            'Aqua',
            'Teal',
            'Turquoise',
            'Lagoon',
            'Crystal',
            'Pearl White',
            'Opal',
            'Quartz',
            'Ruby',
            'Emerald',
            'Sapphire',
            'Diamond',
            'Topaz',
            'Jade',
            'Amber Glow',
            'Citrine',
            'Carnelian',
            'Garnet',
            'Tourmaline',
            'Moonstone',
        ];

        foreach ($patterns as $pattern) {
            PuppyPattern::create([
                'name' => $pattern,
            ]);
        }
    }
}
